[platform.windows.x86_64]
version = "0.2.1"
sha256 = "36d28593ba8932a0c731b3a985f4b60b75e620ce10610f60d350daac49ec4a2e"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-windows-x86_64.eop"
environment = ">=0.4.1"

[platform.windows.arm64]
version = "0.2.1"
sha256 = "86561215102a83e987095ce2c8ee56ecbe3ec063992387d08e01f230c00087d4"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-windows-arm64.eop"
environment = ">=0.4.1"

[platform.linux.arm64]
version = "0.2.1"
sha256 = "f07a3161a75ed91f5d2c6b7672a4eadf58d9068aa364db40e63071b504889b82"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-linux-arm64.eop"
environment = ">=0.4.1"

[platform.linux.x86_64]
version = "0.2.1"
sha256 = "76f874d85cad216dfc1e6d5b4b0a02c754285753a459ba2baab5802b472610dc"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-linux-x86_64.eop"
environment = ">=0.4.1"

[platform.macos.arm64]
version = "0.2.1"
sha256 = "9e8628f3dc5db2ba5e27c44b00db603342143628f4158e42d0df4d6ddaee4cae"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-macos-arm64.eop"
environment = ">=0.4.1"

[platform.macos.x86_64]
version = "0.2.1"
sha256 = "e63d0f865e4c96892357d5a408015ac284a76c56fc29a020bfb4c0a48b9a5127"
url = "https://github.com/eosin-platform/eov-annotations-plugin/releases/download/v0.2.1/annotations-v0.2.1-macos-x86_64.eop"
environment = ">=0.4.1"

